### ISSUE TITLE
therionsurface2survex not generating output

### ISSUE THREAD

**Issue by jonnyprouty** [hbeni/therionsurface2survex#1]
Thanks so much for releasing this, @hbeni . I'm hoping it will replace my current nasty shell script which converts AAIGrid to therion surfaces. The addition of the survex surface will be lovely! Unfortunately, I've not been able to generate any output for my data.

I've successfully built the linux target and have been able to process the example you provide. When I attempt to use therionsurface2survex on my own data however, the program exits prematurely. When run with -d, it prints "DBG:8: " followed by a bunch of elevation data, then simply returns to a shell prompt. This happens when I provide as input an existing therion surface file or the AAIGrid file from which the surface file was manually created.

My input data is much larger than the example data, which I suspect is causing the issue. I hope this report helps, I am really looking forward to incorporating your program into my workflow. I have attached both the AAIGrid which is causing the issue and the equivalent therion surface definition.

Thanks in advance!

[surface.zip](https://github.com/hbeni/therionsurface2survex/files/6029733/surface.zip)

**Comment by hbeni** [comment]
I have found the bug.
- when parsing the `surface.th` file the parser does not recognize the negative stepsize `-9.436974789915967`
Btw, i'm not sure this is valid data... why is the stepsize negative?
And why is the stepsize not round?
Therion processes your surface data fine, i guess?
- when parsing the gdal file, the file misses the `cellsize` header.
For this i just added some code that prints an error with the missing headers.
You should be able to parse `surface.grid` file by adding `cellsize     9.446043165468` before the data.

**Comment by hbeni** [comment]
(reopened for further investigation about a) negative grid specs and b) floats in the grid command)

**Comment by jonnyprouty** [comment]
>     * when parsing the `surface.th` file the parser does not recognize the negative stepsize `-9.436974789915967`
>       Btw, i'm not sure this is valid data... why is the stepsize negative?

Ah, good catch. This is a byproduct of how I am obtaining the step size from the original data. I call gdalinfo on the ascii grid file, which I pipe into sed and parse out the "Pixel Size" line. The stepsize is negative in the source data, which I ultimately derived from a DEM provided by the US Forest Service, IIRC. Example below:
```
Driver: AAIGrid/Arc/Info ASCII Grid
Files: surface.grid
Size is 139, 119
Origin = (589908.000000000000000,3856093.000000000000000)
Pixel Size = (9.446043165468000,-9.436974789916000)
Corner Coordinates:
Upper Left  (  589908.000, 3856093.000) 
Lower Left  (  589908.000, 3854970.000) 
Upper Right (  591221.000, 3856093.000) 
Lower Right (  591221.000, 3854970.000) 
Center      (  590564.500, 3855531.500) 
Band 1 Block=139x1 Type=Float32, ColorInterp=Undefined
  NoData Value=-3.40282306073709653e+38
```
 >       And why is the stepsize not round?

I'm not sure, it's whatever was in the raw data. Before converting to an ASCII grid I can resample to a whole number step size if that would make things easier.

>      Therion processes your surface data fine, i guess?

As it turns out, no it doesn't. It plots the grid mirrored, as you can imagine with the negative step size. I'm guessing that when I originally generated this surface for Therion I caught that behavior and manually removed the negative sign, as the surface that has been used with this project has been correct for some time. I haven't generated a new surface recently, until trying to use
therionsurface2survex. I hope that mistake on my part didn't cost you too much time.

>     * when parsing the gdal file, the file misses the `cellsize` header.
>       For this i just added some code that prints an error with the missing headers.
>       You should be able to parse `surface.grid` file by adding `cellsize     9.446043165468` before the data.

Thanks very much for this, this is easy enough to fix on my end!

**Comment by jonnyprouty** [comment]
Incidentally, I just pulled and tested your change. As expected, I received an error on the uncorrected grid data. Adjusting the data also works as expected. Moving forward, I'll resample the original elevation data so that the input for therionsurface2survex does not contain asymetrical pixels.

**Comment by hbeni** [comment]
> I hope that mistake on my part didn't cost you too much time.

No worries!
I just want to get my code right :)

> Moving forward, I'll resample the original elevation data so that the input for therionsurface2survex does not contain asymetrical pixels.

I think that is required by therion.
But maybe at least the not-round size may be supported by it, as might be negative coordinates.

**Comment by hbeni** [comment]
> > Moving forward, I'll resample the original elevation data so that the input for therionsurface2survex does not contain asymetrical pixels.
> 
> I think that is required by therion.
> But maybe at least the not-round size may be supported by it, as might be negative coordinates.

I re-read the manual, assymetrical pixels should be supported. I will add code to deal with the dx/dy headers.

EDIT: Just committed c56b25dea3158, do you want to give it a shot?
The negative stepsize I currently try to clarify with the therion mailing list.

**Comment by hbeni** [comment]
Another go: e7e97e3
I rewrote the header parsing to be more safe (previously there were corner cases when trying to figure out if data was valid; thats assured now)

**Comment by hbeni** [comment]
RE: negative stepsize

thbook says:
> <x spacing> <y spacing> ▷ distance between grid nodes in W-E and S-N directions

So I'm pretty confident that stepsize should not be negative.

**Comment by hbeni** [comment]
And another one: e8bba8c
This adds support for negative bounding box coordinates.

**Comment by hbeni** [comment]
@jonnyprouty any results with the latest commit in master? :)

**Comment by jonnyprouty** [comment]
I have not yet had a chance to test this, but I'm hoping to get to it in
the next few hours!

**Comment by jonnyprouty** [comment]
> @jonnyprouty any results with the latest commit in master? :)

Ok, I've been able to test it. Looks good! Thanks so much for putting in the work to support my weird data!

**Comment by hbeni** [comment]
Cool, thanks for the quick feedback.
I close this then and prepare a new release.
