### ISSUE TITLE
Support therion `grid-flip` command

### ISSUE THREAD

**Issue by hbeni** [hbeni/therionsurface2survex#2]
Therion book, p. 31:
> `grid-flip (none)/vertical/horizontal` ▷ useful if your grid (exported from other
program) needs to be flipped

This should be included in the output file if given in the source.

Test cases:
- flipped grid from therion
- Flipped grid from gdal (negative step size?)

**Comment by hbeni** [comment]
Revisited: `grid-flip` does not need to go into the centerline target data.

What might be needed is the recognizing of the command and then handle it (step size for output reversed?)
https://github.com/hbeni/therionsurface2survex/blob/4bf987718ab969c1154677b6c12c5ac0af9d5a89/therionsurface2survex.cxx#L321

----

EDIT: probably we just need to alter the fixed station generation code.
Station names and coords can remain the same, but the target altitude needs the be looked up different.::
https://github.com/hbeni/therionsurface2survex/blob/4bf987718ab969c1154677b6c12c5ac0af9d5a89/therionsurface2survex.cxx#L358-L377

**Comment by jonnyprouty** [comment]
@hbeni , have you pushed this change yet? Let me know when you have, I'll test it. It didn't occur to me to use the grid-flip option, instead I've been adjusting my data directly.

**Comment by hbeni** [comment]
No, not yet.
I don't even have code for that, so flipping manually is the best option currently.

<s>I'm honestly not even sure this is a thing the tool should do: you can advise therion manually to flip it by adding the respective option in the generated dataset...</s>

**Comment by hbeni** [comment]
I tried to read up a bit on the subject, and indeed, i think the command must be honored by the code.

When for example `grid-flip` vertical is given, in think the resulting grid must be flipped vertically. Therion and survex can’t do that, therionsurface2survex creates absolute station coordinates (centerline data, not grid data).

this will take some time and testing, i guess.

**Comment by hbeni** [comment]
@jonnyprouty It would be cool if you could provide me:
a) input data
b) expected output grid (aven 3d export)

so i can compare the result and make sure i get this right...

**Comment by hbeni** [comment]
@jonnyprouty i have test code in the branch here: [`Issue_2-flipMesh`](https://github.com/hbeni/therionsurface2survex/tree/Issue_2-flipMesh)

In my view, the example test mesh is flipped just fine, with combinations of therions `grid-flip` commands, as well as with negative GDAL stepsizes.

See here (top: horizontally+vertically flipped; bottom: originaldata/unflipped).
I made the test mesh assymetric, so this is clearly visible (see marked intersections):
![grafik](https://user-images.githubusercontent.com/13608602/109473751-05fa0b00-7a74-11eb-9858-acd917a1164c.png)

**Comment by jonnyprouty** [comment]
> @jonnyprouty It would be cool if you could provide me:
> a) input data
> b) expected output grid (aven 3d export)
> 
> so i can compare the result and make sure i get this right...

I will get you some data as soon as possible. Thanks for tackling this!
